version: 2
jobs:
  build:
    docker:
      - image: ishikocpp/gcc-boost:9.1.0-1.70.0
    steps:
      - run: 
          name: "Set ISHIKO_CPP environment variable and create directory"
          command: mkdir /Ishiko-cpp && echo 'export ISHIKO_CPP="/Ishiko-cpp"' >> $BASH_ENV
      - checkout:
          path: /Ishiko-cpp/Process
      - run:
          name: Build
          command: cd /Ishiko-cpp/Process/Makefiles/GNUmakefile && make
